/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface MeuComponente {
        "activated": boolean;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMeuComponenteElement extends Components.MeuComponente, HTMLStencilElement {
    }
    var HTMLMeuComponenteElement: {
        prototype: HTMLMeuComponenteElement;
        new (): HTMLMeuComponenteElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "meu-componente": HTMLMeuComponenteElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface MeuComponente {
        "activated"?: boolean;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "meu-componente": MeuComponente;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "meu-componente": LocalJSX.MeuComponente & JSXBase.HTMLAttributes<HTMLMeuComponenteElement>;
        }
    }
}
